export const AVATAR = require('./man.png')
export const USER_ICON = require('./user.png')
export const GOOGLE_ICON = require('./google-symbol.png')
export const FACEBOOK_ICON = require('./facebook.png')
export const ADDRESS_ICON = require('./address_icon.png')
export const BIRTHDAY_ICON = require('./birthday_icon.png')
export const PHONE_ICON = require('./phone_icon.png')
export const GENDER_ICON = require('./gender_icon.png')